<?php

$collection = $block->getFeedback();

if ($collection) {
    ?>
    <div class="container">

        <h2 class="name"><?= $collection->getData()['firstName'].' '.$collection->getData()['lastName'] ?></h2>

        <div class="comment">
            <h3>
                <?= $collection->getfeedback() ?>
            </h3>
        </div>
        <a href=<?php echo $block->setAcceptUrl($collection->getemail()); ?>>Accept</a>
        <a href=<?php echo $block->setRejectUrl($collection->getemail()); ?>>Reject</a>

    </div>
    <?php
}
?>
